### ISSUE TITLE
Cppcheck Travis job does nothing in a verbose way

### ISSUE THREAD

**Issue by pdimov** [boostorg/function#21]
The Cppcheck job (https://travis-ci.org/boostorg/function/jobs/432021217) fills the Travis log with warnings about a function not being inlined, then concludes with the final blow of:
```
cppcheck: error: could not find or open any of the paths given.
```
and succeeds.

I can't help but notice that Function had a perfectly serviceable .travis.yml configuration which I had put in place, that admittedly needed to be brought up to date but nevertheless provided much more platform coverage (important for a widely used library such as Function.) This has been deleted. Consider reinstating it.

**Comment by jeking3** [comment]
This was done to get coverage and static analysis builds.  We can expand the matrix (however, extended platform testing is done on the test matrix systems).  If the builds don't take too long we can add more platforms.

**Comment by jeking3** [comment]
I will pull the CI from assign here to improve CI.

**Comment by pdimov** [comment]
Thanks!

Have you looked at the Cppcheck job by the way, per the issue title? It seemed to just emit an error and not actually check anything. If you follow the link in the first comment, then open the raw log (https://api.travis-ci.org/v3/job/432021217/log.txt) because the many warnings exceed the displayed log size, you'll see that the invocation prints
```
cppcheck: error: could not find or open any of the paths given.
```
and there's no indication that it analyzed anything.

**Comment by jeking3** [comment]
I will take a look.  Thanks.

**Comment by jeking3** [comment]
@pdimov found it, fixed it, you'll see it in the next PR.
