### ISSUE TITLE
Upgrade to 1.85 causes arg1_type to be missing

### ISSUE THREAD

**Issue by martin5233** [boostorg/function#51]
When compiling the following snippet with older Boost versions, everything is OK:

```
#include <boost/function.hpp>

using ArgType = typename boost::function<int(int)>::arg1_type;
```

However with Boost 1.85 it yields an error 
```
/scratch/apel/new_arch/develop/src/ooa/main_support/test.cpp:7:53: error: ‘arg1_type’ in ‘class boost::function<int(int)>’ does not name a type
    7 | using ArgType = typename boost::function<int(int)>::arg1_type;
```

The same applies for the other arguments, if the prototype has multiple arguments. From my understanding this is a regression.

**Comment by pdimov** [comment]
You're right, this is a regression. I'll fix it.
